### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: No parse factory registered for type ITableMapper with key "tables" (Mapper)

### ISSUE THREAD

**Issue by kmac23va** [Sitecore/experience-extractor#17]
I'm getting this error, when I don't have any post-processor displayed, or a similar one with "msaccess" if I use the UI, which defaults to that setting. I went through the wiki and installed the Access engine it specified, but that didn't help either. I asked about it on Sitecore StackExchange as well: https://sitecore.stackexchange.com/questions/5735/sitecore-experience-extractor-no-parse-factory-registered-for-type-itablemappe. 

```
System.Collections.Generic.KeyNotFoundException: No parse factory registered for type ITableMapper with key "tables" (Mapper)
   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in C:\Projects\ExperienceExtractor\experience-extractor\src\ExperienceExtractor\Api\Parsing\JsonJobParser.cs:line 63
   at ExperienceExtractor.Api.Jobs.Job.<>c__DisplayClass73_0.<Run>b__0(Int32 i) in C:\Projects\ExperienceExtractor\experience-extractor\src\ExperienceExtractor\Api\Jobs\Job.cs:line 133
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ExperienceExtractor.Api.Jobs.Job.Run() in C:\Projects\ExperienceExtractor\experience-extractor\src\ExperienceExtractor\Api\Jobs\Job.cs:line 119

{
  "Id": "c917bee7-8613-4b5b-9f93-2902790da3ea",
  "Created": "2017-05-17T11:50:34.4414859-04:00",
  "Ended": "2017-05-17T11:50:34.4434844-04:00",
  "ItemsProcessed": 0,
  "RowsCreated": 0,
  "Progress": null,
  "Status": "Failed",
  "StatusText": "System.Collections.Generic.KeyNotFoundException: No parse factory registered for type ITableMapper with key \"tables\" (Mapper)\r\n   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JsonJobParser.cs:line 63\r\n   at ExperienceExtractor.Api.Jobs.Job.<>c__DisplayClass73_0.<Run>b__0(Int32 i) in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 133\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 119",
  "SizeLimitExceeded": false,
  "Url": "/sitecore/experienceextractor/jobs/c917bee7-8613-4b5b-9f93-2902790da3ea",
  "Specification": "{\r\n  \"source\": {\r\n    \"xdb\": {\r\n      \"filters\": [\r\n        {\r\n          \"limit\": 1000\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"mapper\": {\r\n    \"tables\": [\r\n      {\r\n        \"name\": \"VisitsByMonth\",\r\n        \"fields\": [\r\n          {\r\n            \"date\": \"month\"\r\n          },\r\n          \"facts\"\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}",
  "LastException": "System.Collections.Generic.KeyNotFoundException: No parse factory registered for type ITableMapper with key \"tables\" (Mapper)\r\n   at ExperienceExtractor.Api.Parsing.JsonJobParser.Parse[TType](ParseState state) in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Parsing\\JsonJobParser.cs:line 63\r\n   at ExperienceExtractor.Api.Jobs.Job.<>c__DisplayClass73_0.<Run>b__0(Int32 i) in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 133\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 119"
}

```

**Comment by kmac23va** [comment]
I installed the wrong version, no issue it seems.
