### ISSUE TITLE
System.InvalidOperationException: The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine.

### ISSUE THREAD

**Issue by biprajit** [Sitecore/experience-extractor#20]
I have installed the package version "ExperienceExtractor-0.3.1-update5-8.1.zip" but getting error while using the tool. Can you please mention exactly what I should include in the "App_Config/ConnectionString.config" in my Sitecore 8.1 instance for using the Experience extractor.
I am getting 100 % complete (Failed) error. The error details is mentioned below:

System.InvalidOperationException: The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine.
   at System.Data.OleDb.OleDbServicesWrapper.GetDataSource(OleDbConnectionString constr, DataSourceWrapper& datasrcWrapper)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at ExperienceExtractor.Components.PostProcessors.AccessExporter.Process(String tempDirectory, IEnumerable`1 tables, IJobSpecification job) in C:\Projects\ExperienceExtractor\experience-extractor\src\ExperienceExtractor.Components\PostProcessors\AccessExporter.cs:line 53
   at ExperienceExtractor.Api.Jobs.Job.Run() in C:\Projects\ExperienceExtractor\experience-extractor\src\ExperienceExtractor\Api\Jobs\Job.cs:line 269

{
  "Id": "746267d0-1f0d-4ac9-b486-d96b0d2b1805",
  "Created": "2018-06-12T11:36:40.7395853+00:00",
  "Ended": "2018-06-12T11:36:46.9842186+00:00",
  "ItemsProcessed": 8092,
  "RowsCreated": 2350,
  "Progress": 1.0,
  "Status": "Failed",
  "StatusText": "System.InvalidOperationException: The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine.\r\n   at System.Data.OleDb.OleDbServicesWrapper.GetDataSource(OleDbConnectionString constr, DataSourceWrapper& datasrcWrapper)\r\n   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)\r\n   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)\r\n   at System.Data.OleDb.OleDbConnection.Open()\r\n   at ExperienceExtractor.Components.PostProcessors.AccessExporter.Process(String tempDirectory, IEnumerable`1 tables, IJobSpecification job) in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor.Components\\PostProcessors\\AccessExporter.cs:line 53\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 269",
  "SizeLimitExceeded": false,
  "Url": "/sitecore/experienceextractor/jobs/746267d0-1f0d-4ac9-b486-d96b0d2b1805",
  "Specification": "{\r\n  \"source\": {\r\n    \"xdb\": {\r\n      \"filters\": [\r\n        {\r\n          \"sample\": 0.3\r\n        },\r\n        {\r\n          \"daterange\": {\r\n            \"start\": \"2018-01-04Z\",\r\n            \"end\": \"2018-06-12Z\"\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  },\r\n  \"mapper\": {\r\n    \"tables\": [\r\n      {\r\n        \"name\": \"Visits\",\r\n        \"fields\": [\r\n          {\r\n            \"date\": \"Date\"\r\n          },\r\n          {\r\n            \"time\": \"Hour\"\r\n          },\r\n          {\r\n            \"xa\": \"Visits/By campaign\"\r\n          },\r\n          {\r\n            \"xa\": \"Visits/By city\"\r\n          },\r\n          {\r\n            \"xa\": \"Visits/By region\"\r\n          },\r\n          \"facts\"\r\n        ],\r\n        \"tables\": []\r\n      }\r\n    ]\r\n  },\r\n  \"postprocessors\": [\r\n    \"msaccess\"\r\n  ]\r\n}",
  "LastException": "System.InvalidOperationException: The 'Microsoft.ACE.OLEDB.12.0' provider is not registered on the local machine.\r\n   at System.Data.OleDb.OleDbServicesWrapper.GetDataSource(OleDbConnectionString constr, DataSourceWrapper& datasrcWrapper)\r\n   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)\r\n   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)\r\n   at System.Data.OleDb.OleDbConnection.Open()\r\n   at ExperienceExtractor.Components.PostProcessors.AccessExporter.Process(String tempDirectory, IEnumerable`1 tables, IJobSpecification job) in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor.Components\\PostProcessors\\AccessExporter.cs:line 53\r\n   at ExperienceExtractor.Api.Jobs.Job.Run() in C:\\Projects\\ExperienceExtractor\\experience-extractor\\src\\ExperienceExtractor\\Api\\Jobs\\Job.cs:line 269"
}

**Comment by estockwell-alpert** [comment]
I have this same issue

**Comment by WongSSJ** [comment]
Did anyone solve this?
